import React from "react";

const NonCashTransfer = () => {
    return (<div className="content">
            <div className="container">
                <div className="content-top">
                    <h1 className="title">VikingBit Cash Transfer Rules</h1>
                </div>
                <div className="content-wrapper bg-opacity">
                    <p><strong>Cash Transfer</strong></p>

                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque convallis sed lectus quis pretium. Cras magna mauris, lacinia eget risus a, tempus laoreet ligula. Vivamus ut pretium lectus. Curabitur rhoncus luctus ullamcorper. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras non leo dolor. Aliquam nec semper dui. Vestibulum in sodales erat. Sed ipsum felis, dictum at nisl eu, accumsan tempus lectus. Aliquam erat volutpat. Donec libero libero, porta et condimentum et, vehicula eget ipsum. In lectus velit, mollis et placerat eget, tempus vitae ligula. Aenean eget sodales mi.</p>

                    <p>Nam nec nisi venenatis, tincidunt ligula in, iaculis augue. Phasellus id nisi mi. Aenean nunc enim, lobortis in imperdiet ac, pulvinar convallis velit. Phasellus mattis lobortis nisi in vulputate. Nunc eu metus convallis, convallis libero id, consectetur massa. Nam non condimentum dui. Suspendisse auctor aliquam consequat. Nam vulputate odio et dui mattis, eu rutrum tortor semper. Proin enim velit, tincidunt et eros ac, vestibulum suscipit elit. Quisque id tempus risus, quis gravida ipsum. Sed malesuada tincidunt tellus a eleifend. Pellentesque eleifend dapibus dapibus. Morbi ac interdum lectus. Sed non pretium est, in semper nibh.</p>

                    <p>Donec interdum erat pulvinar nunc bibendum luctus. Proin gravida eros eget felis pretium, at porta nulla cursus. Maecenas posuere ipsum urna, a dapibus leo vehicula vel. Vestibulum congue diam sit amet odio ultrices ullamcorper. Nam auctor, lacus laoreet efficitur vulputate, odio velit aliquet metus, pellentesque viverra enim nulla sit amet augue. Donec consequat dapibus nisi nec malesuada. Nam sed nulla pretium, laoreet ex in, porttitor augue. Quisque congue nisl lacus, id maximus libero vulputate vel. Nulla elementum vitae sapien a porta. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Etiam nisl augue, consectetur quis ligula sed, mollis mattis magna. Proin volutpat dolor quis dolor vehicula, sit amet aliquam lectus dapibus. Mauris tincidunt laoreet arcu non sodales. Etiam interdum auctor metus, ac hendrerit mi varius ut. Suspendisse ut sollicitudin orci, eu porttitor turpis. Morbi est eros, cursus a sodales sed, tempus a ante.</p>

                    <p>Etiam aliquet felis in sem malesuada, sed pretium metus finibus. Mauris iaculis volutpat ligula. In ut nulla ex. Morbi vitae volutpat tortor, in cursus est. Pellentesque posuere tincidunt eros at porttitor. Nullam rutrum ligula in lacinia sodales. Mauris consequat lectus sed consequat congue. Integer id nulla et enim ullamcorper elementum sit amet ut odio.</p>

                    <p>Phasellus consequat faucibus ante, sit amet pulvinar ipsum facilisis et. Cras nec lacinia diam. Sed sit amet nisl vel sapien congue rutrum. Nulla euismod volutpat elit commodo mollis. Aliquam venenatis pulvinar viverra. Morbi convallis odio sed ligula vulputate, a vestibulum mi sagittis. Ut eu magna non massa egestas consequat. Suspendisse vulputate congue purus ac tempus. Morbi non dictum sem. Quisque ultrices eros ex, id euismod turpis semper sed. Nulla sed gravida arcu, vel dapibus dui.</p>

                    <p>Proin posuere fermentum sodales. Proin feugiat felis eget feugiat facilisis. Aliquam nec enim at sem consequat varius. In imperdiet dolor eu justo venenatis, eu sollicitudin sapien hendrerit. Cras tellus ante, tristique lacinia dignissim ut, eleifend in nulla. Cras quis pulvinar dolor. Maecenas felis ante, mollis id leo sit amet, blandit mattis quam.</p>

                    <p>Nunc pulvinar leo sit amet dapibus volutpat. Proin at commodo augue. Ut ultricies lacinia quam sit amet ultricies. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed ut imperdiet felis, nec feugiat quam. Vestibulum iaculis, odio sed elementum pellentesque, est lacus bibendum odio, eget elementum justo arcu congue neque. Vivamus suscipit venenatis orci nec semper. Proin pulvinar pellentesque augue vel condimentum. Sed volutpat blandit lacinia. Praesent luctus, magna sit amet efficitur fringilla, sapien quam viverra mauris, nec rutrum purus lectus in enim.</p>

                    <p>Donec at mauris congue massa port a egestas. Sed ornare dolor malesuada, mattis nisl et, sagittis mi. Phasellus ultricies quam a est porttitor, vel hendrerit turpis pulvinar. Etiam sit amet varius libero. Nam consequat ante et diam pellentesque, nec consectetur justo scelerisque. Proin rhoncus, justo vitae sagittis tincidunt, augue ex vestibulum dui, vehicula facilisis risus orci id mauris. Aenean faucibus, libero et tempus tempor, nisi mauris pharetra nibh, nec mattis ipsum leo nec mauris. Nunc in scelerisque augue. Sed sed nisl rhoncus, euismod orci ut, vehicula ligula. Donec ultrices orci at felis dapibus, eget tempus eros vulputate. Curabitur condimentum velit in eros fringilla euismod. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed tincidunt velit id urna sollicitudin, id efficitur velit condimentum. Nunc sodales ex sit amet est faucibus, quis venenatis neque sagittis. Duis vitae malesuada mi. Suspendisse suscipit orci purus, ut finibus magna eleifend nec.</p>

                    <p>Aenean non nunc fermentum, hendrerit ipsum eleifend, auctor metus. Quisque convallis urna sed purus posuere, eu dictum arcu vestibulum. Aliquam aliquet, nibh non tempor tincidunt, nibh arcu feugiat magna, at luctus purus dui in justo. Nulla porta ornare nulla, quis egestas leo rhoncus eu. Morbi non eros sit amet neque molestie euismod. Praesent nunc orci, bibendum nec efficitur quis, euismod vel neque. Ut quis ipsum a mauris ultrices luctus quis sit amet felis. Suspendisse potenti. Sed consectetur ac libero et dapibus. Mauris vitae arcu sit amet magna accumsan cursus. In porta lacus turpis, vulputate gravida erat vestibulum at. Donec et tincidunt nisl. Nulla est orci, venenatis et ultrices ac, pharetra quis mi. Integer magna est, varius non arcu ac, placerat fringilla enim.</p>

                    <p>Vivamus accumsan, dolor at vestibulum gravida, lorem massa condimentum purus, vitae sollicitudin eros eros non metus. Nulla non tellus enim. Vestibulum pulvinar leo sed ante fermentum, eu rhoncus mauris elementum. Nam sed nulla turpis. Aliquam suscipit ullamcorper diam, sed auctor lorem vulputate non. Vivamus accumsan massa eu nibh bibendum, nec tristique libero varius. Suspendisse eu sem scelerisque, consectetur eros eget, porta mi. Nulla a turpis vel sem rutrum imperdiet vel non mauris. Praesent tincidunt euismod molestie. In at nibh suscipit, rhoncus ante in, mollis ex. Proin auctor, diam a suscipit varius, turpis lacus mattis ex, at molestie turpis felis laoreet est. Donec sit amet justo laoreet, scelerisque turpis et, aliquam ipsum. Phasellus id erat risus. Phasellus ac sem vel sem elementum efficitur.</p>

                    <p>Proin elementum scelerisque lacinia. Aenean sed ante malesuada, molestie justo at, scelerisque justo. Mauris in urna justo. Duis blandit justo eu ex interdum, a lobortis tortor aliquam. Cras libero diam, tristique ac luctus eu, interdum sit amet metus. Ut id ultrices diam, sit amet bibendum neque. Vestibulum sem tortor, hendrerit nec facilisis placerat, feugiat vitae tellus. Nunc facilisis porta tortor vel tempus. Nullam at ante eros.</p>

                    <p>Vestibulum non dignissim turpis. Sed interdum nibh sed mattis condimentum. Maecenas ac ligula at magna lacinia mattis. Aenean nisl nisl, efficitur eget volutpat sed, venenatis at dolor. Phasellus ante ipsum, pellentesque a nisl id, congue tincidunt augue. Nulla sollicitudin ligula id est fermentum luctus. Aenean ut eleifend ligula. Integer sapien ante, ornare at venenatis finibus, ultrices et eros. Suspendisse lobortis nulla mauris, quis vehicula justo accumsan quis. Donec rhoncus massa nec erat gravida, sed elementum nisl volutpat. Etiam egestas blandit felis.</p>

                    <p>Suspendisse egestas turpis elit. Vivamus imperdiet nulla dapibus placerat sollicitudin. Aenean et dolor ultricies, consequat purus a, finibus elit. Mauris est lacus, sodales sed posuere ac, laoreet a libero. Donec rhoncus ante vel justo consectetur, ut iaculis dolor scelerisque. Nullam tellus mi, tempus non augue in, sodales tincidunt neque. Phasellus imperdiet dictum dui eget consequat. Duis ligula elit, ultricies vel semper quis, mattis nec leo. Pellentesque mollis eu eros auctor egestas. Morbi porttitor ac duieu bibendum. Duis dui urna, sagittis in erat eget, tempus elementum risus. Nam id finibus augue.</p>

                    <p>Donec elementum vehicula tortor non tristique. Nulla facilisis neque vitae finibus luctus. Sed aliquam, risus pharetra ullamcorper scelerisque, ligula magna aliquet ipsum, eu convallis elit massa et ligula. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Maecenas libero enim, pellentesque sed libero ac, consectetur euismod tortor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Duis in ultricies augue. Donec feugiat a lacus vel tincidunt. Vivamus condimentum finibus maximus. Etiam feugiat ligula eget consequat dignissim. Mauris dolor tellus, convallis nec lacus eget, pulvinar auctor erat. Pellentesque sit amet justo nec erat laoreet placerat. In consequat libero sem, non feugiat urna tempor quis. Sed at posuere nulla.</p>

                    <p>Morbi tincidunt nec diam in varius. Ut consequat neque vel vulputate bibendum. Maecenas nisl magna, congue non nibh et, varius vulputate elit. Nunc scelerisque urna ac condimentum molestie. Aliquam iaculis dapibus turpis eu posuere. Nullam a dignissim diam. Suspendisse sed tincidunt turpis, vel sagittis quam. Nullam volutpat sit amet justo eu interdum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed erat mi, laoreet vel libero non, rhoncus aliquet dolor. Nullam maximus facilisis massa. Aenean at pretium est.</p>

                    <p>Integer vitae facilisis leo. Phasellus auctor ante quis accumsan posuere. Proin non magna vel lectus scelerisque porta. Cras sit amet metus ac metus scelerisque auctor. In elit ex, faucibus at arcu vel, tincidunt dignissim dolor. Fusce faucibus sem eu lacus ultricies iaculis. Donec eget convallis risus. Phasellus consequat arcu eros, in blandit orci facilisis nec. Donec gravida vitae sem vel fermentum. Ut rutrum sapien et tortor feugiat sollicitudin. Proin pretium placerat pulvinar. Curabitur convallis dolor non fringilla commodo. Suspendisse quis nibh eget urna finibus faucibus non a eros. Aliquam volutpat sagittis bibendum. Ut nec consectetur metus, condimentum maximus ante. Maecenas turpis metus, rutrum eget efficitur id, vulputate vel est.</p>

                    <p>Proin tincidunt erat nec venenatis interdum. Duis vestibulum non felis tincidunt viverra. Sed eu tincidunt mi. Quisque congue diam vel risus sagittis tristique. Quisque pretium iaculis porttitor. Suspendisse eleifend eros dolor, ut porta quam maximus ac. Sed fermentum tortor eget neque placerat, ac facilisis enim commodo. Praesent eget dolor tellus. Etiam mollis, orci vitae ornare varius, lorem quam tempor massa, ac hendrerit erat diam vel lectus. Curabitur mattis purus at tempor sollicitudin. Pellentesque congue metus vitae enim molestie, ac lobortis enim dignissim. Aliquam facilisis mattis massa at faucibus. Maecenas at nulla lacus. Aliquam ipsum nisi, vestibulum ac lacinia eu, volutpat in lacus. Pellentesque nec ex enim. Nullam a euismod ante.</p>

                    <p>Maecenas egestas elit justo, in eleifend ante feugiat sit amet. Nullam nec ligula dignissim, euismod est sit amet, porta erat. Fusce vel sapien sit amet libero lacinia aliquam. Nam mattis quis lectus non rutrum. Curabitur vel nisi nec mauris volutpat posuere. Curabitur tempor ante at ullamcorper sodales. Nullam pellentesque erat eget nisi molestie condimentum eget dapibus tellus. Fusce ex sapien, interdum nec felis sed, commodo pellentesque risus. Proin iaculis condimentum diam at sodales. Mauris ac lorem quis magna malesuada condimentum at dictum tortor. Nam at dolor augue. Donec hendrerit lacus ac urna auctor suscipit maximus et urna. Maecenas blandit tortor facilisis dui gravida, id sollicitudin odio consequat. Cras pharetra condimentum luctus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Suspendisse potenti.</p>

                    <p>Praesent porttitor quis enim ut ornare. Etiam ut massa sollicitudin, elementum ipsum in, facilisis ex. Suspendisse at augue lacinia, pellentesque nisl eget, accumsan lectus. Duis eget malesuada ipsum. Donec sagittis lobortis varius. Maecenas tincidunt enim quis lacus accumsan pulvinar. Cras odio velit, volutpat at purus et, porttitor vulputate enim. Donec dictum laoreet risus, eget finibus elit sodales vel. Sed nec sem augue. Nam nec cursus justo. Suspendisse nibh sem, cursus eu elementum at, pharetra vel nisl. Pellentesque a mauris sit amet risus lobortis tristique nec at dolor. Cras accumsan turpis vitae risus commodo facilisis. Cras faucibus congue lectus ut sodales. Donec volutpat et neque vel placerat.</p>

                    <p>Cras vitae sapien lorem. Suspendisse potenti. Maecenas ornare at dolor nec luctus. Praesent pulvinar feugiat tristique. Vivamus vel magna gravida, rhoncus leo sed, rutrum orci. Nullam non luctus erat. Phasellus aliquet urna lacus, eu tincidunt tellus consectetur non.</p>

                    <p>Duis consectetur malesuada magna. Phasellus lobortis accumsan eros non laoreet. Aliquam erat volutpat. Ut scelerisque est vel nunc ultrices auctor. Morbi vehicula nisl non tincidunt molestie. Ut eget eros ex. Pellentesque arcu libero, volutpat in porta quis, viverra eget nisl. Nulla elit ex, consectetur quis sem ut, gravida tempus metus.</p>

                    <p>Quisque a arcu vel lacus semper ultrices gravida non ipsum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aliquam hendrerit facilisis nulla posuere fringilla. Fusce laoreet nibh lacus, eu volutpat nisi convallis in. Curabitur a convallis lorem, eu maximus erat. Donec lorem elit, auctor ut turpis vel, placerat fermentum libero. Cras malesuada mi sed velit vulputate porttitor. Maecenas est tortor, faucibus a metus eu, eleifend efficitur nisl. In vel felis ut risus lobortis malesuada vel nec orci. Praesent at faucibus ante. Maecenas condimentum purus libero, vel mattis mauris pharetra rutrum. Sed id posuere dui. Sed lacus mauris, dapibus ac venenatis in, lobortis vel orci. Aenean tristique augue non fringilla commodo. Ut sollicitudin aliquam tincidunt.</p>

                    <p>Integer in nisi rutrum, efficitur magna vitae, maximus odio. Nullam diam dolor, venenatis at ultricies in, convallis vel libero. Phasellus pulvinar interdum elementum. Sed aliquam enim at dolor accumsan, eget laoreet lacus suscipit. Etiam iaculis mollis lacinia. In feugiat diam ultricies, eleifend nisi sagittis, feugiat sapien. Aliquam efficitur libero non rhoncus vehicula. Nam vehicula orci ut sapien bibendum congue. Nunc pharetra pulvinar venenatis. Nulla mollis orci magna, luctus congue lectus commodo id. Nulla ipsum eros, tincidunt non ornare ac, tempus a nisl. Maecenas enim orci, porta sed tortor eget, imperdiet tristique eros.</p>

                    <p>Nulla vel mauris arcu. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris porta ullamcorper justo id auctor. Pellentesque sed odio quam. Nunc in ipsum at turpis consequat vehicula. Vestibulum vitae tempor augue, nec maximus tortor. Aenean luctus fermentum luctus.</p>

                    <p>Fusce scelerisque tellus congue, venenatis velit sit amet, molestie purus. Aenean a varius purus. Mauris pulvinar elit ligula, ut congue diam tristique a. Integer sit amet nunc tempor quam pulvinar commodo ut vitae est. Fusce et enim non urna ultrices euismod id ut ipsum. Maecenas placerat feugiat velit a aliquet. Quisque sed lorem mollis, interdum dolor a, convallis risus. Suspendisse scelerisque odio nunc. Pellentesque suscipit tellus at dolor efficitur, aliquam ultrices dui sollicitudin. Suspendisse venenatis sit amet turpis vel molestie. Nullam non mi est. Fusce auctor lobortis posuere. Donec pretium metus ac justo faucibus, ac posuere mauris tincidunt. Etiam eget porttitor magna. Sed faucibus urna non turpis efficitur, sit amet commodo tellus placerat. Praesent eu euismod turpis.</p>

                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque tempor tincidunt ante ut finibus. Nam vel justo ac nisi volutpat porta eget a mauris. Sed at velit feugiat, pharetra arcu dignissim, ultricies mi. Nunc iaculis nibh quis sem tincidunt elementum. Suspendisse nec nulla pellentesque, venenatis erat ut, sagittis enim. Sed consequat ante non quam gravida aliquam. Quisque vulputate elit neque, ut ullamcorper sapien tincidunt eu. Suspendisse mattis tempus auctor.</p>

                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras pharetra lacus eget elit pellentesque, non pharetra nisl blandit. Aenean ex justo, rutrum in molestie eget, bibendum sit amet eros. Nunc vitae suscipit velit. Aenean porta, lectus quis interdum viverra, neque risus suscipit lectus, egestas porttitor nunc dolor in felis. Proin et elit in diam auctor consectetur. Aliquam at ipsum hendrerit, auctor ipsum quis, laoreet lorem. Donec hendrerit non ipsum eu gravida. Pellentesque faucibus elit ut lacus rutrum efficitur. Nulla leo nunc, eleifend in tellus vitae, finibus mollis metus. Interdum et malesuada fames ac ante ipsum primis in faucibus. In eget massa sit amet ex aliquet imperdiet.</p>

                    <p>Proin sapien justo, pretium a felis dictum, aliquam placerat justo. Donec justo nibh, gravida vel turpis a, faucibus gravida tortor. Nam sit amet tristique libero, a gravida ex. Nulla nulla ex, feugiat sollicitudin mi at, fringilla pulvinar erat. Cras in porta urna, et iaculis nisi. Vivamus et ullamcorper nunc. Fusce interdum a neque bibendum tempor. Fusce vitae vulputate tellus. Nam nec tortor vestibulum turpis finibus tempor. Nam metus eros, tempor quis turpis nec, suscipit egestas justo. Nulla pellentesque rhoncus sem quis bibendum. Sed cursus, diam iaculis finibus cursus, metus lectus interdum orci, id egestas massa augue in ligula. Fusce in dolor nibh. Maecenas luctus odio vestibulum pulvinar facilisis. Nulla facilisi. Sed ullamcorper sapien ipsum, sed facilisis nisl tincidunt vel.</p>

                    <p>Curabitur massa dui, luctus in lorem non, dignissim placerat augue. Aenean vel cursus odio. Phasellus euismod risus nulla, vel dapibus mi posuere ut. Nam viverra in nunc in blandit. Nam felis neque, molestie eu neque quis, auctor laoreet tortor. Sed ornare lorem id lacinia suscipit. Phasellus cursus ultricies dui, vulputate hendrerit dolor consectetur eu. Donec justo urna, blandit vitae sagittis a, venenatis nec justo. Nam ac lacus rutrum, viverra elit vitae, porta purus. Vestibulum libero ex, tristique sit amet ultricies eget, elementum maximus est. Integer pretium magna ut commodo auctor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Maecenas eu tempus dolor. Vestibulum facilisis purus et ipsum auctor, sed volutpat lectus finibus. Nullam scelerisque vestibulum ex, quis mollis ante viverra sit amet.</p>

                    <p>Donec tempus aliquam libero, vel placerat ligula. Fusce et orci sollicitudin, mattis velit at, luctus est. Nullam arcu odio, malesuada quis mi vel, hendrerit vestibulum lorem. Donec tellus nisi, pulvinar id scelerisque congue, finibus et enim. Vestibulum suscipit eleifend nisi quis tristique. Maecenas eu nibh quis enim hendrerit placerat. Pellentesque molestie nec tortor id accumsan. Phasellus facilisis ipsum eget mauris convallis, eget sollicitudin libero faucibus. Etiam vehicula et nisl et finibus.</p>

                </div>
            </div>
        </div>
    );
};

export default NonCashTransfer;